"""add appointment followups table

Revision ID: 0818995813be
Revises: 84a30c504eff
Create Date: 2026-04-03 20:24:12.847982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0818995813be'
down_revision = '84a30c504eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_followups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appointment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('was_completed', sa.Boolean(), nullable=False),
    sa.Column('outcome_type', sa.Enum('normal', 'anomaly', 'unknown', name='appointment_outcome_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_followups_appointment_id'), ['appointment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointment_followups_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_followups_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_followups_appointment_id'))

    op.drop_table('appointment_followups')
    # ### end Alembic commands ###
