"""add user_settings table

Revision ID: 692f041e94ce
Revises: 900a07c0913c
Create Date: 2026-05-11 16:00:29.165889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692f041e94ce'
down_revision = '900a07c0913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_7_days', sa.Boolean(), nullable=False),
    sa.Column('reminder_3_days', sa.Boolean(), nullable=False),
    sa.Column('reminder_same_day', sa.Boolean(), nullable=False),
    sa.Column('reminder_2_hours', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    # ### end Alembic commands ###
