"""add weight, blood_pressure, glucose, fetal_movement tables

Revision ID: 900a07c0913c
Revises: 0818995813be
Create Date: 2026-05-11 15:45:27.727162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900a07c0913c'
down_revision = '0818995813be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_pressure_measurements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('gestational_week', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_pressure_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_pressure_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('fetal_movement_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('gestational_week', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetal_movement_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetal_movement_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('glucose_measurements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fasting_value', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('postprandial_value', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gestational_week', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glucose_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glucose_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('weight_measurements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gestational_week', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_measurements_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_measurements_user_id'))

    op.drop_table('weight_measurements')
    with op.batch_alter_table('glucose_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glucose_measurements_user_id'))

    op.drop_table('glucose_measurements')
    with op.batch_alter_table('fetal_movement_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetal_movement_sessions_user_id'))

    op.drop_table('fetal_movement_sessions')
    with op.batch_alter_table('blood_pressure_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_pressure_measurements_user_id'))

    op.drop_table('blood_pressure_measurements')
    # ### end Alembic commands ###
